### ISSUE TITLE
Facebook preview image

### ISSUE THREAD

**Issue by rayhaanj** [davidjrichardson/uwcs-zarya#30]
When pasting a URL into a Facebook™ post, it arbitrarily picks an image to use as the preview image. It may appear better if the UWCS™logo is used as the default image, to ensure consistent user experience.

It appears that this can be done by using some Open Graph XML tags in the page.

See http://stackoverflow.com/a/6693576 for an example.

**Comment by RhiannonMichelmore** [comment]
I second this, it annoys me too!
