### ISSUE TITLE
Where does this syntax come from?

### ISSUE THREAD

**Issue by jai-sharma** [davidjrichardson/uwcs-zarya#36]
https://github.com/davidjrichardson/uwcs-zarya/blob/fca4df27943ccc843983ef8a968894264dc03c1e/events/templates/events/events_index_page.html#L19

Not really an issue, just really confused, sorry ('-')/

**Comment by rayhaanj** [comment]
` <h5 class="week-title">Week beginning {{ week.0.start|first_monday|date:'jS F Y' }}</h5>`

I believe it's Django's template syntax for passing values through some functions. Takes the start of the first upcoming week and passes it through the `first_monday` [function](https://github.com/davidjrichardson/uwcs-zarya/blob/master/events/templatetags/event_tags.py) 

```python
@register.filter
def first_monday(event_date):
    year = event_date.isocalendar()[0]
    week = event_date.isocalendar()[1]
    d = date(year, 1, 4)  # The Jan 4th must be in week 1  according to ISO
    return d + timedelta(weeks=(week - 1), days=-d.weekday())
```

Then finally renders the date with the [date builtin function](https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#date).

**Comment by davidjrichardson** [comment]
@rayhaanj nailed it on the head -- it's just django templating syntax and a custom filter.

**Comment by jai-sharma** [comment]
Thanks ('-')/

**Comment by jai-sharma** [comment]
Oh wow, custom template tags, that's cool
