### ISSUE TITLE
User's real names are public and uneditable

### ISSUE THREAD

**Issue by twpol** [davidjrichardson/uwcs-zarya#43]
The public profile page for each user, visible whenever they sign up to an event, include that user's real name. E.g. mine is https://uwcs.co.uk/accounts/profile/1027/.

Issues:
* The private version of the profile page (https://uwcs.co.uk/accounts/profile/) doesn't display your real name.
* The edit profile page (https://uwcs.co.uk/accounts/profile/update/) doesn't let you change your real name.

**Comment by davidjrichardson** [comment]
This has been addressed in the commits leading up to 565ebbdf9b4727e33812fe55fbc02e9c182d9df9
